
:- multifile schemafile/2, class/4, extension/4, property/5, method/6, gmethod/7.
:- dynamic schemafile/2, class/4, extension/4, property/5, method/6, gmethod/7.
:- assert(schemafile('MyDB','schema.pl')).

:- assert(class(databaseId,fullclassNameUpper,fullclassName,baseclassName)).
:- assert(class(databaseId,shortclassNameUpper,fullclassName,baseclassName)).
:- assert(class('MyDB','STARCOUNTER.ENTITY','Starcounter.Entity','none')).
:- assert(class('MyDB','ENTITY','Starcounter.Entity','none')).
:- assert(class('MyDB','STARCOUNTER.USERDOMAIN','Starcounter.UserDomain','Starcounter.Entity')).
:- assert(class('MyDB','USERDOMAIN','Starcounter.UserDomain','Starcounter.Entity')).
:- assert(class('MyDB','STARCOUNTER.USER','Starcounter.User','Starcounter.Entity')).
:- assert(class('MyDB','EXAMPLE2.PERSON','Example2.Person','Starcounter.Entity')).
:- assert(class('MyDB','PERSON','Example2.Person','Starcounter.Entity')).
:- assert(class('MyDB','EXAMPLE.LOCATION','Example.Location','Starcounter.Entity')).
:- assert(class('MyDB','LOCATION','Example.Location','Starcounter.Entity')).
:- assert(class('MyDB','EXAMPLE.DEPARTMENT','Example.Department','Starcounter.Entity')).
:- assert(class('MyDB','DEPARTMENT','Example.Department','Starcounter.Entity')).
:- assert(class('MyDB','EXAMPLE.PERSON','Example.Person','Starcounter.Entity')).
:- assert(class('MyDB','PERSON','Example.Person','Starcounter.Entity')).
:- assert(class('MyDB','EXAMPLE.EMPLOYEE','Example.Employee','Example.Person')).
:- assert(class('MyDB','EMPLOYEE','Example.Employee','Example.Person')).
:- assert(extension(databaseId,fullclassName,fullextensionNameUpper,fullextensionName)).
:- assert(extension(databaseId,fullclassName,shortextensionNameUpper,fullextensionName)).
:- assert(extension('MyDB','Example.Person','EXAMPLE.MYPERSON','Example.MyPerson')).
:- assert(extension('MyDB','Example.Person','MYPERSON','Example.MyPerson')).
:- assert(extension('MyDB','Example.Employee','EXAMPLE.MYPERSON','Example.MyPerson')).
:- assert(extension('MyDB','Example.Employee','MYPERSON','Example.MyPerson')).
:- assert(property(databaseId,fullclassName,propertyNameUpper,propertyName,propertyType)).
:- assert(property(databaseId,fullextensionName,propertyNameUpper,propertyName,propertyType)).
:- assert(property('MyDB','Starcounter.UserDomain','NAME','Name','String')).
:- assert(property('MyDB','Starcounter.User','CULTURE','Culture','String')).
:- assert(property('MyDB','Starcounter.User','DOMAIN','Domain','Starcounter.UserDomain')).
:- assert(property('MyDB','Starcounter.User','ISENABLED','IsEnabled','Boolean')).
:- assert(property('MyDB','Starcounter.User','NAME','Name','String')).
:- assert(property('MyDB','Starcounter.User','PASSWORD','Password','String')).
:- assert(property('MyDB','Starcounter.User','HASPASSWORD','HasPassword','Boolean')).
:- assert(property('MyDB','Example2.Person','NICKNAME','NickName','String')).
:- assert(property('MyDB','Example.Location','NAME','Name','String')).
:- assert(property('MyDB','Example.Location','DESCRIPTION','Description','String')).
:- assert(property('MyDB','Example.Location','TYPE','Type','Int32')).
:- assert(property('MyDB','Example.Department','NAME','Name','String')).
:- assert(property('MyDB','Example.Department','DESCRIPTION','Description','String')).
:- assert(property('MyDB','Example.Department','LOCATION','Location','Example.Location')).
:- assert(property('MyDB','Example.Department','IDBINARY','IdBinary','Binary')).
:- assert(property('MyDB','Example.Person','FIRSTNAME','FirstName','String')).
:- assert(property('MyDB','Example.Person','LASTNAME','LastName','String')).
:- assert(property('MyDB','Example.Person','_TEMP','_Temp','String')).
:- assert(property('MyDB','Example.Person','HOME','Home','Example.Location')).
:- assert(property('MyDB','Example.Person','FATHER','Father','Example.Person')).
:- assert(property('MyDB','Example.Person','MOTHER','Mother','Example.Person')).
:- assert(property('MyDB','Example.Employee','FIRSTNAME','FirstName','String')).
:- assert(property('MyDB','Example.Employee','LASTNAME','LastName','String')).
:- assert(property('MyDB','Example.Employee','_TEMP','_Temp','String')).
:- assert(property('MyDB','Example.Employee','HOME','Home','Example.Location')).
:- assert(property('MyDB','Example.Employee','FATHER','Father','Example.Person')).
:- assert(property('MyDB','Example.Employee','MOTHER','Mother','Example.Person')).
:- assert(property('MyDB','Example.Employee','HIREDATE','HireDate','DateTime')).
:- assert(property('MyDB','Example.Employee','COMMISSION','Commission','Boolean')).
:- assert(property('MyDB','Example.Employee','SALARYSBYTE','SalarySByte','SByte')).
:- assert(property('MyDB','Example.Employee','SALARYINT16','SalaryInt16','Int16')).
:- assert(property('MyDB','Example.Employee','SALARYINT32','SalaryInt32','Int32')).
:- assert(property('MyDB','Example.Employee','SALARYINT64','SalaryInt64','Int64')).
:- assert(property('MyDB','Example.Employee','SALARYBYTE','SalaryByte','Byte')).
:- assert(property('MyDB','Example.Employee','SALARYUINT16','SalaryUInt16','UInt16')).
:- assert(property('MyDB','Example.Employee','SALARYUINT32','SalaryUInt32','UInt32')).
:- assert(property('MyDB','Example.Employee','SALARYUINT64','SalaryUInt64','UInt64')).
:- assert(property('MyDB','Example.Employee','SALARYDECIMAL','SalaryDecimal','Decimal')).
:- assert(property('MyDB','Example.Employee','SALARYSINGLE','SalarySingle','Single')).
:- assert(property('MyDB','Example.Employee','SALARYDOUBLE','SalaryDouble','Double')).
:- assert(property('MyDB','Example.Employee','MANAGER','Manager','Example.Employee')).
:- assert(property('MyDB','Example.Employee','DEPARTMENT','Department','Example.Department')).
:- assert(property('MyDB','Example.MyPerson','MYID','MyId','Int32')).
:- assert(property('MyDB','Example.MyPerson','MYNAME','MyName','String')).
:- assert(property('MyDB','Example.MyPerson','STARTDATE','StartDate','DateTime')).
:- assert(property('MyDB','Example.MyPerson','ENDDATE','EndDate','DateTime')).
:- assert(method(databaseId,fullName,methodNameUpper,methodName,argumentTypes,returnType)).
:- assert(method('MyDB','Starcounter.Entity','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Starcounter.UserDomain','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Starcounter.User','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Example2.Person','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Example.Location','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Example.Department','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Example.Person','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(method('MyDB','Example.Employee','EQUALSORISDERIVEDFROM','EqualsOrIsDerivedFrom',['Starcounter.IObjectView'],'Boolean')).
:- assert(gmethod(databaseId,fullName,methodNameUpper,methodName,typeParameters,argumentTypes,returnType)).
:- assert(gmethod('MyDB','Example.Person','GETEXTENSION','GetExtension',['Example.MyPerson'],[],'Example.MyPerson')).
:- assert(gmethod('MyDB','Example.Employee','GETEXTENSION','GetExtension',['Example.MyPerson'],[],'Example.MyPerson')).
