
using System;
using System.Collections.Generic;
using System.IO;

namespace Starcounter.Server.Compiler
{
    /// <summary>
    /// Define the result of <c>AppCompiler.Compile()</c>.
    /// </summary>
    public sealed class AppCompilerResult
    {
        readonly string appName;

        /// <summary>
        /// Referenced assemblies that has been copied to the 
        /// <c>OutputDirectory</c>.
        /// </summary>
        internal readonly IList<string> PrivateReferenceAssemblies = new List<string>();
        
        /// <summary>
        /// Full path to directory where the compiled app reside.
        /// </summary>
        public string OutputDirectory { get; private set; }

        /// <summary>
        /// Full path to the compiled application executable.
        /// </summary>
        public string ApplicationPath {
            get {
                return Path.Combine(OutputDirectory, $"{appName}.exe");
            }
        }

        /// <summary>
        /// Full path to the application symbol file.
        /// </summary>
        public string SymbolFilePath {
            get {
                return Path.Combine(OutputDirectory, $"{appName}.pdb");
            }
        }

        /// <summary>
        /// All artifacts generated by the compiler, including the application,
        /// the symbol file and any binaries copied locally.
        /// </summary>
        public IEnumerable<string> Artifacts {
            get {
                var all = new List<string>(PrivateReferenceAssemblies);
                all.Add(ApplicationPath);
                all.Add(SymbolFilePath);
                return all;
            }
        }

        internal AppCompilerResult(string name, string directory)
        {
            if (string.IsNullOrEmpty(name)) {
                throw new ArgumentNullException(nameof(name));
            }

            if (string.IsNullOrEmpty(directory)) {
                throw new ArgumentNullException(nameof(directory));
            }

            if (!Directory.Exists(directory))
            {
                throw new DirectoryNotFoundException($"Directory {directory} dont exist");
            }

            appName = name;
            OutputDirectory = directory;
        }
    }
}
